nelmio_api_doc:
    documentation:
        info:
            title: Restaurant API
            description: Documentation de l'API Restaurant Studi
            version: 1.0.0
        components:
            securitySchemes:
                apitoken:                    # ← Nom sans tirets
                    type: apiKey
                    name: X-AUTH-TOKEN       # ← Le vrai nom du header
                    in: header
        security:
            - apitoken: []                   # ← Référence au schéma ci-dessus
    areas:
        path_patterns:
            - ^/api(?!/doc$)